
export enum MusicActionTypes{
    // Fetching many music
    FETCH_MANY_MUSIC = "FETCH_MANY_MUSIC", 
    STORE_MANY_MUSIC = "STORE_MANY_MUSIC",
    FETCH_MANY_MUSIC_ERROR = "FETCH_MANY_MUSIC_ERROR",

    // Fetching single music
    FETCH_SINGLE_MUSIC = "FETCH_MANY_MUSIC",
    STORE_SINGLE_MUSIC = "STORE_SINGLE_MUSIC",
    FETCH_SINGLE_MUSIC_ERROR = "FETCH_SINGLE_MUSIC_ERROR",
    
    SET_PLAYING = "SET_PLAYING"
}